config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  match 'blobs/:signed_id/*filename', to: 'blobs#show', via: [:get, :post]
  delete 'attachments/:signed_id/*filename', to: 'attachments#destroy'
  resources :attachments, only: [:destroy], as: :destroy_attachment
  resources :posts
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_rich_text :content
  has_one_attached :main_image
  has_many_attached :other_images

  def attach_other_images(signed_blob_id)
    blob = ActiveStorage::Blob.find_signed(signed_blob_id)
    return other_images.attach(signed_blob_id) unless blob.present?

    other_images.attach(blob.signed_id) unless other_images.attachments.map(&:blob_id).include?(blob.id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController
  def destroy
    @blob = id.present? ? ActiveStorage::Attachment.find(id).blob : ActiveStorage::Blob.find_signed(signed_id)

    # We are doing this in a transaction because we don't want anything to change if something fails
    @blob.transaction do
      if any_attachments?
        # The way we are handling blobs, they will always only have a single attachment
        # https://github.com/rails/rails/blob/v6.0.0.rc2/activestorage/app/javascript/activestorage/direct_upload.js#L22
        attachment = @blob.attachments.first
        @record_name = attachment.name
        @record = attachment.record_type.constantize.find(attachment.record_id)

        attachment.purge_later
      end

      # Destroy the blob that doesn't have any attachments
      @blob.purge unless any_attachments?

      # We need to update the new content coming through in the case that the user's
      # internet connection drops or if the page is reloaded after the XHR request
      @record.update_attribute(:content, content) if should_update?
    end

    respond_with nil do |format|
      format.html { destroy_redirect }
      format.json { head :no_content }
    end
  end

  private

  def attachment_params
    params.permit(:id, :post_id, :signed_id, :filename, :content)
  end

  def id
    attachment_params[:id]
  end

  def content
    attachment_params[:content]
  end

  def post_id
    attachment_params[:post_id]
  end

  def signed_id
    attachment_params[:signed_id]
  end

  def any_attachments?
    @blob.attachments.any?
  end

  def should_update?
    @record&.respond_to?(:content) && @record_name != 'main_image'
  end

  def destroy_redirect
    redirect_to post_id.present? ? edit_post_url(post_id) : posts_path
  end
end

app/controllers/blobs_controller.rb
# frozen_string_literal: true

class BlobsController < ActiveStorage::BlobsController
  def show
    return super unless @blob.image?

    redirect_to @blob.variant(resize: '250x250').processed.service_url(disposition: params[:disposition])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    attach_other_images if @post.save
    respond_with @post
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    attach_other_images if @post.update(post_params)
    respond_with @post
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_with @post
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.with_attached_other_images.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :posted_at, :content, :main_image, other_images: [])
  end

  def attach_other_images
    return unless params[:other_images].present?

    params[:other_images].each do |signed_blob_id|
      @post.attach_other_images(signed_blob_id)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/blobs_helper.rb
# frozen_string_literal: true

module BlobsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveStoragePlayground</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if post.id? %>
    <%= tag.input type: 'hidden', name: 'post_id', value: post.id, id: 'post-id' %>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :posted_at %>
    <%= form.datetime_select :posted_at %>
  </div>

  <div class="field">
    <%= form.label :main_image %>
    <%= form.file_field :main_image %>
  </div>

  <% if post.main_image.attached? %>
    <p>
      <%= link_to 'Remove Main Image', "#{destroy_attachment_path(post.main_image.id)}?post_id=#{post.id}", method: 'delete', data: { confirm: 'Delete the main image attachment?' } %>
    </p>

    <div>Current main image: </div>
    <%= image_tag post.main_image.variant(resize: '200x200') %>
    <%= tag.input type: 'hidden', name: 'post[main_image]', value: post.main_image.blob.signed_id %>
  <% end %>

  <% post.other_images.each do |other| %>
    <%= tag.input type: 'hidden', name: 'post[other_images][]', value: other.blob.signed_id %>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Posted date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.posted_at %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<% if @post.main_image.attached? %>
  <div>
    <%= image_tag @post.main_image.variant(resize: '400x400') %>
  </div>
<% end %>

<div>
  <%= @post.content %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>